name: CI
on: push

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: "12.x"
    
    - name: Get yarn
      run: npm i -g yarn
    
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
    - name: Get Statik
      run: go get github.com/rakyll/statik

    - name: Build
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        make build
      
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: app
        path: ./app
